name: Documentation
on:
  push:
    branches:
      - master
      - main

jobs:
  docs:
    name: Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # fake pages
      - name: Gen dummy page
        run: |
          mkdir public
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>GitHub Pages deployed!</title>
            </head>
            <body>
              <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
            </body>
          </html>
          EOL

#      # https://github.com/marketplace/actions/github-pages
#      - name: Deploy to GitHub Pages
#        uses: crazy-max/ghaction-github-pages@v2
#        if: github.event_name == 'push'
#        with:
#          target_branch: gh-pages
#          build_dir: docs/public
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
