name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#          version: v1.33

      - name: Get dependencies GGGG
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test
